version: "3.3"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static
    depends_on:
      - backend

volumes:
  static:
  data: